---
- name: Configure firewall (Debian and Ubuntu)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ allowed_tcp_ports }}"
  when: ansible_os_family == 'Debian'

- name: Configure default ufw policy
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
    state: enabled
  with_items:
  - { direction: outgoing, policy: allow }
  - { direction: incoming, policy: deny }
  when: ansible_os_family == 'Debian'

- name: Enable ufw
  ufw:
    state: enabled
  when: ansible_os_family == 'Ubuntu'

- name: Configure firewall (CentOS)
  firewalld:
    state: "{{ item.state }}"
    port: "{{ item.port }}"
    zone: public
    immediate: yes
    permanent: yes
  with_items: 
  - { state: 'enabled', port: '22/tcp' }
  - { state: 'enabled', port: '80/tcp' }
  - { state: 'enabled', port: '443/tcp' }
  when: ansible_os_family == 'RedHat'