nginx_config:
  only:
    - main
  script:
    - echo $ANSIBLE_VAULT_PASSWORD > .vault_password.txt
    - chmod 400 .vault_password.txt
    - ansible-playbook -i inventory/inv.ini --vault-password-file .vault_password.txt playbooks/main.yml
  after_script:
    - rm .vault_password.txt