Nginx config:
  only:
    - main
  script:
    - echo $ANSIBLE_VAULT_PASSWORD > .vault_password.txt
    - ansible-playbook -i inventory/inv.ini --vault-password-file .vault_password.txt playbooks/mail.yml