stages:
  - "pre_check"
  - "deploy"

nginx_config_check:
  rules:
  - changes:
    - "*.md"
    when: never
  - when: always
  only:
  - main
  stage: pre_check
  script:
    - echo $ANSIBLE_VAULT_PASSWORD > .vault_password.txt
    - chmod 400 .vault_password.txt
    - ansible-playbook -i inventory/inv.ini --vault-password-file .vault_password.txt main.yml --syntax-check
  after_script:
    - rm .vault_password.txt

nginx_config_deploy:
  rules:
  - changes:
    - "*.md"
    when: never
  - when: always
  only:
    - main
  stage: deploy
  script:
    - echo $ANSIBLE_VAULT_PASSWORD > .vault_password.txt
    - chmod 400 .vault_password.txt
    - ansible-playbook -i inventory/inv.ini --vault-password-file .vault_password.txt main.yml
  after_script:
    - rm .vault_password.txt