---
- hosts: all
  become: true

  vars_files:
    - vars/vars.yml
    - /etc/ansible/vault/nginx.yml

  handlers:
  - name: reload Nginx
    service:
      name: Nginx
      state: reload

  pre_tasks:
  - name: Update apt cache if needed.
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_os_family == 'Debian'

  tasks:
  - name: trigger initial system wide update (Debian)
    apt:
      upgrade: yes
    when: ansible_os_family == 'Debian'
  
  - name: trigger initial system wide update (CentOS 7)
    yum:
      name: '*'
      state: latest
    when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "7"

  - name: trigger initial system wide update (CentOS 8+)
    dnf:
      name: '*'
      state: latest
    when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] >= "8"  

  - name: Set timezone
    community.general.timezone:
      name: Asia/Barnaul
      
  - name: Install required package
    package:
      name:
      - net-tools
      - curl
      - wget
      - nano
      - vim
      - mc
      state: present
  - name: Install bmon (for Ubuntu/Debian)
    package:
      name:
      - bmon
      state: present
      when: ansible_os_family == 'Debian'